steps:
  # Build test image.
  - name: "gcr.io/kaniko-project/executor:latest"
    id: "build-test"
    args:
      - "--context=dir://."
      - "--destination=europe-west1-docker.pkg.dev/$PROJECT_ID/industry/idp-test"
      - "--cache=true"
      - "--build-arg=TEST=true"

  # Formatter.
  - name: "europe-west1-docker.pkg.dev/$PROJECT_ID/industry/idp-test"
    id: "formatter"
    dir: "."
    waitFor: ["build-test"]
    entrypoint: "black"
    args: ["--check", "."]

  # Linter.
  - name: "europe-west1-docker.pkg.dev/$PROJECT_ID/industry/idp-test"
    id: "linter"
    dir: "."
    waitFor: ["build-test"]
    entrypoint: "pylint"
    args:
      - testname/
      - bin/
      - tests/

  # Unit Tests.
  - name: "europe-west1-docker.pkg.dev/$PROJECT_ID/industry/idp-test"
    id: "unit-test"
    dir: "."
    waitFor: ["build-test"]
    entrypoint: "pytest"

  - name: "gcr.io/kaniko-project/executor:latest"
    waitFor:
      ["formatter", "linter",  "unit-test"]
    args:
      - "--context=dir://."
      - "--destination=europe-west1-docker.pkg.dev/$PROJECT_ID/industry/idp"
      - "--cache=true"

timeout: 900s
